general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/usr/bin/bash"

[window]
padding = { x = 15, y = 15 }
# opacity = 0.75

[font]
size = 8.0

[env]
TERM = "xterm-256color"

[terminal]
